# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首頁
    url: '/'
    weight: 10
  - name: 課程
    weight: 20
    identifier: courses
  - name: 894-231 華語簡報與口語表達
    PageRef: course/232_ch-oral-presentation/_index.md
    weight: 10
    parent: courses
  - name: 894-112 基礎華語二
    PageRef: course/232_ch-2/_index.md
    weight: 10
    parent: courses
  - name: 894-361 跨境電商專案
    PageRef: course/232_ch-ecommerce
    weight: 10
    parent: courses
  - name: 關於講師
    PageRef: authors/chungche-huang/
    weight: 30
